### PR TITLE
Features/yaml config

### PR DESCRIPTION
**Pull request by hugolgst**
@anned20 Please continue creating PRs in order to avoid breaking master, I let you pick up this PR

### CODE REVIEW

**Comment by anned20** [comment]
I agree, I thought I had done that for the latest commit, but apparently I was wrong.

I don't understand why you merged out 3 commits, while only the latest commit has breaking changes.

**Comment by hugolgst** [comment]
I think it is a better practice to create PRs even for minor changes, what do you think?

**Comment by anned20** [comment]
I agree with that too.

**Comment by hugolgst** [comment]
And after each PR is made we can request the review from each other and/or groups such as `@vimsence/maintainers`

**Pull request closed without merging**
